var num1 = 3.14;
var num2 = -10;
var num3 = 0;
var num4 = 5;
var string1 = 'coding';
var string2 = 'Google';
var string3 = "USA";
var boolean1 = true;
var boolean2 = false;
var undefined = haha123;
console.log("The first number is", num1);
console.log("The second number is", num2);
console.log("The third number is", num3);
console.log("The fourth number is", num4);
console.log("The first string is", string1);
console.log("The second string is", string2);
console.log("The third string is", string3);
console.log("The first boolean is", boolean1);
console.log("The second boolean is", boolean2);
console.log("The undefined variable is", undefined);
